import type MarkdownIt from "markdown-it";

/**
 * markdown-it plugin for rendering KaTeX formulas generated by the GPT series LLM
 * @param md MarkdownIt instance
 * @param options Plugin options
 */
declare function markdownItKatexGpt(md: MarkdownIt, options?: MarkdownItKatexGptOptions): void;

/**
 * delimiter display config item
 */
interface DelimiterItem {
  left: string
  right: string
  display: boolean
}

/**
 * Plugin Options
 */
interface MarkdownItKatexGptOptions {
  /**
   * delimiters display configuration
   */
  delimiters: DelimiterItem[]
}

export default markdownItKatexGpt;